### ISSUE TITLE
Trim leading whitespaces from factoid query

### ISSUE THREAD

**Issue by Maldivia** [evanchooly/javabot#177] opened 2017-09-07 08:14 UTC
If you add a whitespace between ~ and the faction, javabot will fail finding it. Example:
```
<Maldivia> | ~ reflection
<javabot>  | Maldivia, what does that even *mean*?
<Maldivia> | ~reflection
<javabot>  | Maldivia, reflection is a set of APIs that allow (...)
```

**Comment by jottinger** [comment] 2017-09-07 09:09
Tested in-channel (see https://javabot.evanchooly.com/logs/%23%23java/2017-09-07#59b10bcc0a975a17e4f0cfe5 )

This looks like it's working; there's also a test that specifically exercises this functionality ( https://github.com/evanchooly/javabot/blob/master/src/test/kotlin/javabot/operations/GetFactoidOperationTest.kt#L129 ) and from what I can tell, there's... something else going on here, but I don't know what it is.

I also tested in privmsg. This looks like not a bug, from the best I can tell. Is there anything else about the interaction that would give us more specifics?

**Comment by Maldivia** [comment] 2017-09-07 10:38
Hmm, it seems I might typed a whitespace that's not ASCII 32 space, since the logs has:
```
Maldivia | ??reflection
Maldivia | Maldivia, what does that even *mean*?
```
https://javabot.evanchooly.com/logs/%23%23java/2017-09-07#59b0fe530a975a17e4f06e7e

Although, I guess that shows another bug/feature -- javabot identifies itself as the user it's addressing in the logs?
Also, ~ are stripped from logs?

**Comment by jottinger** [comment] 2017-09-07 11:18
Can you file a separate (set of?) issues for that? *THIS* issue is inaccurate (although maybe we could trim alt-space too? What character code is that?)

**Comment by Maldivia** [comment] 2017-09-07 11:44
String.trim is simple in the sense, that it only removed characters in the U+0000 .. U+0020 range, but does nothing with unicode whitespaces.

Perhaps change to ignore `if (c <= ' ' || Character.isSpaceChar(c))`, which would have removed the `'\u00A0'`, which I typed in this case.

For list of unicode spaces: http://www.fileformat.info/info/unicode/category/Zs/list.htm

**Comment by jottinger** [comment] 2017-11-07 19:23
I'm closing this issue as we've been unable to confirm the outlier case.

**Closed by jottinger** 2017-11-07 19:23 UTC
