### ISSUE TITLE
BotOperationComparator can go

### ISSUE THREAD

**Issue by rzwitserloot** [evanchooly/javabot#192] opened 2017-11-10 14:18 UTC
BotOperation now have an internal method for ordering (method 'getPriority()'); therefore BotOperationComparator is now unused and can be deleted. It's also technically buggy (it would answer '1' when you ask it to compare 'AddFactoid' and 'AddFactoid' which breaks the contract. You can't actually make javabot mess up with this, it's a spec failure that's unlikely to ever result in a real bug, but, still. Extra reason to delete it).

**Comment by jottinger** [comment] 2017-11-10 14:19
Duplicate of #190

**Closed by jottinger** 2017-11-10 14:19 UTC
