### ISSUE TITLE
Would be nice to have a ~previnfo or other way to restore an overwritten factoid.

### ISSUE THREAD

**Issue by rzwitserloot** [evanchooly/javabot#169] opened 2016-12-03 16:46 UTC
_feature request_

When some hooligan overwrites a factoid, or it is done accidentally, it would be nice if we can in-channel look up what just got overwritten.

This can take the form of: `~restore <factoid name>`
or: `~previnfo <factoid name>`

or something else.

**Comment by evanchooly** [comment] 2016-12-03 23:40
I wrote this a while back for that very reason but I haven't integrated it to the bot yet:  https://github.com/evanchooly/lariat

**Comment by evanchooly** [comment] 2017-05-23 19:41
duplicate of #16

**Closed by evanchooly** 2017-05-23 19:41 UTC
